[package]
name = "feather_of_despair"
version = "0.1.0"
authors = ["time"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.98.0"
byteorder = "^1.3.4"
enum_primitive = "0.1.1"
num = "0.3.0"
