- job:
    name: featherofdespair-build
    pre-run: playbooks/build/pre.yaml
    run: playbooks/build/run.yaml
    voting: false
    roles:
      - zuul: opendev/zuul-jobs

- project:
    check: &id001
      jobs:
        - featherofdespair-build
    gate: *id001
    post-merge: *id001
